import React, { useState } from 'react';
import { BarChart, Bar, Cell, XAxis, YAxis, Tooltip, ResponsiveContainer } from 'recharts';
import { SBCard, SBChip, SBStat, SBButton, SBIcon } from '../../../components/primitives';
import {
  formatPeriodRange,
  formatUnixShort,
  isoWeekNumber,
  pickStat,
  fmtPercent,
  fmtInt,
  deriveHeadline,
} from '../lib/format.js';

// The core detail-view layout, ported from the UI kit `ReportsView`.
// Used on its own in ReportDetail and twice in ReportCompare.
export default function ReportView({
  report,
  trendReports,   // optional: last N reports of same kind, for the bar chart
  compact,        // render as a compare-column (narrower, smaller headline)
  onCompare,      // callback, shown as "Compare to previous period" if provided
  onAskLara,    // callback, shown as "Ask Lara to synthesize"
}) {
  const [showRaw, setShowRaw] = useState(false);

  if (!report) {
    return (
      <SBCard style={{ padding: 28 }}>
        <div className="sb-label" style={{ marginBottom: 8 }}>Report</div>
        <div style={{ color: 'var(--sb-fg-4)', fontSize: 13 }}>No report loaded.</div>
      </SBCard>
    );
  }

  const newLeads = pickStat(report.stats, 'leads.new_leads_count');
  const hot = pickStat(report.stats, 'leads.hot_count');
  const reply = pickStat(report.stats, 'automations.reply_rate');
  const forecast = pickStat(report.stats, 'forecast');
  const sources = pickStat(report.stats, 'leads.sources', []);
  const headline = deriveHeadline(report);
  const paragraphs = (report.narrative || '').split(/\n\n+/).filter(Boolean);

  const barData = Array.isArray(trendReports) && trendReports.length > 0
    ? trendReports.map((r) => ({
        label: `W${isoWeekNumber(r.period_start_unix)}`,
        value: pickStat(r.stats, 'leads.new_leads_count', 0) || 0,
        current: r.id === report.id,
      }))
    : [];

  const maxSource = Array.isArray(sources) && sources.length > 0
    ? Math.max(...sources.map((s) => Number(s.count) || 0), 1)
    : 1;

  const sourceColors = [
    'var(--sb-accent)', 'var(--sb-violet)', 'var(--sb-warm)',
    'var(--sb-cool)', 'var(--sb-lime)',
  ];

  const headlineSize = compact ? 26 : 40;
  const chartGrid = compact ? '1fr' : '1.4fr 1fr';

  return (
    <div>
      {/* Eyebrow */}
      <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 8, flexWrap: 'wrap' }}>
        <span className="sb-label" style={{ color: 'var(--sb-accent)' }}>
          {`Week ${isoWeekNumber(report.period_start_unix)} \u00B7 ${formatPeriodRange(report)}`}
        </span>
        <SBChip tone="violet" icon="lara">
          {`Generated by Lara \u00B7 ${report.model || 'haiku-4.5'}`}
        </SBChip>
        {report.has_embedding === false && (
          <span style={{ fontSize: 10.5, color: 'var(--sb-fg-5)', fontFamily: 'var(--sb-font-mono)' }}>
            {'\u25B8 search disabled for this report'}
          </span>
        )}
      </div>

      {/* Headline */}
      <h1 style={{
        fontFamily: 'var(--sb-font-display)', fontSize: headlineSize, fontWeight: 600,
        letterSpacing: '-0.03em', margin: '0 0 24px', lineHeight: 1.05,
      }}>
        {headline}
      </h1>

      {/* Narrative card */}
      <div className="sb-brackets" style={{
        padding: '26px 28px', background: 'var(--sb-card)', marginBottom: 28, maxWidth: compact ? '100%' : 860,
      }}>
        {paragraphs.length === 0 ? (
          <p style={{ fontSize: 14, color: 'var(--sb-fg-4)', margin: 0, lineHeight: 1.6 }}>
            {'Narrative pending \u2014 Haiku call may have failed. Try regenerate.'}
          </p>
        ) : (
          paragraphs.slice(0, 2).map((p, i) => (
            <p
              key={i}
              style={{
                fontSize: i === 0 ? 16 : 14,
                lineHeight: 1.65,
                color: i === 0 ? 'var(--sb-fg-2)' : 'var(--sb-fg-3)',
                margin: i === 0 ? 0 : '14px 0 0',
              }}
            >
              {p}
            </p>
          ))
        )}
      </div>

      {/* 4-stat strip */}
      <div style={{
        display: 'grid', gridTemplateColumns: compact ? 'repeat(2, 1fr)' : 'repeat(4, 1fr)',
        gap: 12, marginBottom: 28,
      }}>
        <SBStat label="New leads" value={fmtInt(newLeads)} mono />
        <SBStat label="Hot leads" value={fmtInt(hot)} mono />
        <SBStat label="Reply rate" value={fmtPercent(reply)} mono />
        <SBStat label="Forecast" value={typeof forecast === 'string' ? forecast : fmtInt(forecast)} mono />
      </div>

      {/* Side-by-side charts */}
      <div style={{ display: 'grid', gridTemplateColumns: chartGrid, gap: 16 }}>
        <SBCard style={{ padding: 22 }}>
          <div className="sb-label" style={{ marginBottom: 14 }}>Leads by week</div>
          {barData.length === 0 ? (
            <div style={{ height: 160, display: 'flex', alignItems: 'center', justifyContent: 'center',
              color: 'var(--sb-fg-5)', fontSize: 12, fontFamily: 'var(--sb-font-mono)' }}>
              Not enough history
            </div>
          ) : (
            <div style={{ height: 160 }}>
              <ResponsiveContainer width="100%" height="100%">
                <BarChart data={barData} margin={{ top: 4, right: 4, left: 0, bottom: 0 }}>
                  <XAxis
                    dataKey="label"
                    axisLine={false}
                    tickLine={false}
                    tick={{ fill: 'var(--sb-fg-5)', fontSize: 9.5, fontFamily: 'var(--sb-font-mono)' }}
                  />
                  <YAxis hide />
                  <Tooltip
                    cursor={{ fill: 'rgba(255,255,255,0.03)' }}
                    contentStyle={{
                      background: 'var(--sb-card-2)',
                      border: '1px solid var(--sb-line-2)',
                      fontSize: 11,
                      fontFamily: 'var(--sb-font-mono)',
                    }}
                    labelStyle={{ color: 'var(--sb-fg-3)' }}
                    itemStyle={{ color: 'var(--sb-fg)' }}
                  />
                  <Bar dataKey="value" radius={0}>
                    {barData.map((entry, i) => (
                      <Cell
                        key={i}
                        fill={entry.current ? 'var(--sb-accent)' : 'var(--sb-card-2)'}
                        stroke={entry.current ? 'var(--sb-accent)' : 'var(--sb-line-2)'}
                      />
                    ))}
                  </Bar>
                </BarChart>
              </ResponsiveContainer>
            </div>
          )}
        </SBCard>

        <SBCard style={{ padding: 22 }}>
          <div className="sb-label" style={{ marginBottom: 14 }}>Top sources</div>
          {!Array.isArray(sources) || sources.length === 0 ? (
            <div style={{ color: 'var(--sb-fg-5)', fontSize: 12, fontFamily: 'var(--sb-font-mono)' }}>
              No source data
            </div>
          ) : (
            <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
              {sources.slice(0, 6).map((r, i) => {
                const count = Number(r.count) || 0;
                const pct = Math.round((count / maxSource) * 100);
                const color = sourceColors[i % sourceColors.length];
                return (
                  <div key={`${r.source}-${i}`}>
                    <div style={{ display: 'flex', justifyContent: 'space-between',
                      fontSize: 11.5, marginBottom: 4, gap: 10 }}>
                      <span style={{ color: 'var(--sb-fg-2)', whiteSpace: 'nowrap',
                        overflow: 'hidden', textOverflow: 'ellipsis' }}>
                        {r.source || 'unknown'}
                      </span>
                      <span style={{ fontFamily: 'var(--sb-font-mono)', color: 'var(--sb-fg-4)',
                        whiteSpace: 'nowrap' }}>{count}</span>
                    </div>
                    <div style={{ height: 4, background: 'var(--sb-panel)' }}>
                      <div style={{ height: '100%', width: `${pct}%`, background: color }} />
                    </div>
                  </div>
                );
              })}
            </div>
          )}
        </SBCard>
      </div>

      {/* Actions */}
      {(onCompare || onAskLara) && (
        <div style={{ display: 'flex', gap: 8, marginTop: 24, flexWrap: 'wrap' }}>
          {onCompare && (
            <SBButton variant="secondary" size="sm" icon="arrow" onClick={onCompare}>
              Compare to previous period
            </SBButton>
          )}
          <SBButton
            variant="ghost" size="sm"
            icon={showRaw ? 'arrowDown' : 'arrow'}
            onClick={() => setShowRaw((v) => !v)}
          >
            {showRaw ? 'Hide' : 'View'} raw stats JSON
          </SBButton>
          {onAskLara && (
            <SBButton variant="primary" size="sm" icon="lara" onClick={onAskLara}>
              Ask Lara to synthesize
            </SBButton>
          )}
        </div>
      )}

      {showRaw && (
        <pre style={{
          marginTop: 16,
          padding: 16,
          background: 'var(--sb-panel)',
          border: '1px solid var(--sb-line-2)',
          fontFamily: 'var(--sb-font-mono)',
          fontSize: 11.5,
          color: 'var(--sb-fg-2)',
          overflow: 'auto',
          maxHeight: 360,
        }}>
{JSON.stringify(report.stats ?? {}, null, 2)}
        </pre>
      )}

      {/* Footer meta */}
      <div style={{
        marginTop: 20, fontFamily: 'var(--sb-font-mono)', fontSize: 10.5,
        color: 'var(--sb-fg-5)', display: 'flex', gap: 16, flexWrap: 'wrap',
      }}>
        <span>generated {formatUnixShort(report.generated_at_unix)}</span>
        <span>prompt {report.prompt_version || 'v1'}</span>
        <span>model {report.model || 'haiku-4.5'}</span>
      </div>
    </div>
  );
}
